### Pegando Admin
GET http://localhost:3000/admin
###

### Pegando Parâmetros com ID
GET http://localhost:3000/admin/250
###

### Acessando Via Post
POST http://localhost:3000/admin
Content-Type: application/json

{
    "login": "lutekdev",
    "senha": "123456"
}

### Acessando Via Path
PATCH http://localhost:3000/admin/250

### Acessando Via Delete
DELETE http://localhost:3000/admin/250